[package]
name = "sys-mount"
version = "1.2.2"
description = "High level FFI binding around the sys mount & umount2 calls"
repository = "https://github.com/pop-os/sys-mount"
authors = ["Michael Aaron Murphy <mmstickman@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["linux", "sys", "mount", "umount"]
categories = ["external-ffi-bindings", "filesystem", "os::unix-apis"]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
bitflags = "1.2"
libc = "0.2"
loopdev = "0.3"

[dev-dependencies]
clap = "2.33"
